name: Test Community Contribution Label

on:
  issues:
    types: [assigned, unassigned]

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Community Contribution Label
        uses: iamshobhraj/.github/.github/workflows/community-contribution-label.yml@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
